### ISSUE TITLE
TransactionInactiveError: Failed to execute 'getAllKeys' on 'IDBObjectStore': The transaction is inactive or finished.

### ISSUE THREAD

**Issue by threesmegiste** [NoelDeMartin/media-kraken#10] opened 2021-01-16 11:25 UTC
[Please explain what you were trying to do when this error appeared.]

Stack trace:
```getAllKeys@[native code]
https://noeldemartin.github.io/media-kraken/js/chunk-vendors.951aeeef.js:58:155702
https://noeldemartin.github.io/media-kraken/js/chunk-vendors.951aeeef.js:58:162280
https://noeldemartin.github.io/media-kraken/js/chunk-vendors.951aeeef.js:58:159190
a@https://noeldemartin.github.io/media-kraken/js/chunk-vendors.951aeeef.js:58:158092
promiseReactionJob@[native code]
```

**Comment by NoelDeMartin** [comment] 2021-01-16 17:38
Hey thanks for opening an issue! I see that the error reporting modal is working :).

Is there any problem that you're having with the application after seeing this error? I've also found something similar to this during development and I haven't been able to reproduce it, but most of the time the app works correctly if you close it and open it again.

**Comment by NoelDeMartin** [comment] 2021-01-25 17:57
I've been looking into this and it seems to be a bug that only happens in Safari [and should be fixed in new versions](https://github.com/jakearchibald/idb/issues/73#issuecomment-755383530).

I have done my best to fix it, but given that I have no Apple device to test it, I'm not sure if the fix actually works. In any case, it should work now and if it doesn't try updating Safari or using a different browser.

**Closed by NoelDeMartin** 2021-01-25 17:57 UTC
