### ISSUE TITLE
Full url used as subject in turtle resource

### ISSUE THREAD

**Issue by bourgeoa** [NoelDeMartin/media-kraken#8] opened 2020-10-12 08:43 UTC
The recent closing of `solid.community` server had the consequence that your app did not work anymore.
I had to rename all the movies using the new `solidcommunity.net` as subject in turtle file.

I tried to make a relative link, but it does not seem to work.
Is it in relation with the service worker ?

**Comment by NoelDeMartin** [comment] 2020-10-12 16:18
Hi there, thanks for opening the issue.

I've been looking into this and most movies are created with absolute urls (which, seeing how things turned out, I'll try to change). But there are some that have relative urls, those are the ones that are marked as watched after adding them. The reason is that for new documents I am using POST so the document is stored as I send it, but for updates I am using PATCH with solid operations and the server must be doing some optimizations to store relative urls.

So relative urls should work, because that's how movies you've modified after adding them to your collection are stored. I'm not sure if it's the service worker's fault, but maybe you can try logging in a different browser to see if it works as expected. I'd also try to log out and log in again because models are cached in the browser to speed up the boot up.

Also, when you say it doesn't work what do you mean? You get an error, or some movies are missing?

**Comment by bourgeoa** [comment] 2020-10-12 18:09
I made relative links with solid-ideI on Forrest Gump has example
Make a search
select watched and got a 500 error

**Comment by NoelDeMartin** [comment] 2020-10-13 06:21
Ok, I'll do some tests to see if I can reproduce it.

In any case, I've been working on a version with improved error reporting so if I haven't been able to reproduce this, I'll let you know when I release the new version to see if we can get more details about the problem.

**Comment by NoelDeMartin** [comment] 2020-11-27 11:12
I just released a [new version](https://github.com/NoelDeMartin/media-kraken/releases/tag/v0.1.4) that not only fixes this for new documents, but also migrates existing data in your POD to have the proper format :). You can read more about how that works here: [Schema Migration](https://github.com/NoelDeMartin/media-kraken/blob/v0.1.4/docs/schema-migration.md).

Let me know if you've got any problems with that.

**Closed by NoelDeMartin** 2020-11-27 11:12 UTC
