### ISSUE TITLE
CSS changed idp location

### ISSUE THREAD

**Issue by bourgeoa** [NoelDeMartin/media-kraken#17] opened 2022-01-12 15:29 UTC
Trying to login to https://solidweb.me/bourgeoa/ with media-kraken it failed with `InvalidRequest: invalid_request`
```
​ GET https://solidweb.me/bourgeoa/profile/ 401
​ GET https://solidweb.me/idp/ 404
 GET https://noeldemartin.github.io/media-kraken/login 404
 Service worker has been registered.
 GET https://solidweb.me/bourgeoa/profile/ 401
​ GET https://solidweb.me/idp/ 404
```
I don't if you were aware of this :
https://gitter.im/solid/community-server?at=617443052197144e8480c4b0

**Comment by NoelDeMartin** [comment] 2022-01-12 19:39
Thanks for raising this issue @bourgeoa,

I just created an account in `solidweb.me` and it seems to work properly, so I'm not sure what's wrong in your case. Can you try using a new browser to see if it works? Chrome in incognito mode should work, for example.

Although looking at the message you linked, maybe the issue exists with accounts that already existed? If that's the case, I'm not sure if I should do anything in my app to address it... I added [a migration script](https://github.com/NoelDeMartin/media-kraken/blob/main/docs/schema-migration.md) when `solid.community` stopped working because a lot of people where using that, but I'm not sure how many people is using accounts with `solidweb.me` and if it's worth it. At least I'd like to understand what exactly changed and how to fix it, but it's difficult to do if I can't reproduce the issue myself.

**Comment by bourgeoa** [comment] 2022-01-12 22:18
Noel
It is working perfectly. I don't understand where the problem was.
I'm on tablet.
I shall check tomorrow on my computer


Le mer. 12 janv. 2022 à 20:39, Noel De Martin ***@***.***> a
écrit :

**Comment by bourgeoa** [comment] 2022-01-14 16:37
Working also perfectly on my computer.

**Comment by NoelDeMartin** [comment] 2022-01-15 07:12
It may have been some temporary error then, I'm going to close this issue then, feel free to reopen if you have any updates.

**Closed by NoelDeMartin** 2022-01-15 07:12 UTC
